import { Card } from '../schema';
import { SUIT_VALUES, CARD_VALUES } from './enums';

const deckOfCards: Card[] = [
  { id: 0, value: CARD_VALUES.THREE, suit: SUIT_VALUES.SPADES },
  { id: 1, value: CARD_VALUES.THREE, suit: SUIT_VALUES.CLUBS },
  { id: 2, value: CARD_VALUES.THREE, suit: SUIT_VALUES.DIAMONDS },
  { id: 3, value: CARD_VALUES.THREE, suit: SUIT_VALUES.HEARTS },
  { id: 4, value: CARD_VALUES.FOUR, suit: SUIT_VALUES.SPADES },
  { id: 5, value: CARD_VALUES.FOUR, suit: SUIT_VALUES.CLUBS },
  { id: 6, value: CARD_VALUES.FOUR, suit: SUIT_VALUES.DIAMONDS },
  { id: 7, value: CARD_VALUES.FOUR, suit: SUIT_VALUES.HEARTS },
  { id: 8, value: CARD_VALUES.FIVE, suit: SUIT_VALUES.SPADES },
  { id: 9, value: CARD_VALUES.FIVE, suit: SUIT_VALUES.CLUBS },
  { id: 10, value: CARD_VALUES.FIVE, suit: SUIT_VALUES.DIAMONDS },
  { id: 11, value: CARD_VALUES.FIVE, suit: SUIT_VALUES.HEARTS },
  { id: 12, value: CARD_VALUES.SIX, suit: SUIT_VALUES.SPADES },
  { id: 13, value: CARD_VALUES.SIX, suit: SUIT_VALUES.CLUBS },
  { id: 14, value: CARD_VALUES.SIX, suit: SUIT_VALUES.DIAMONDS },
  { id: 15, value: CARD_VALUES.SIX, suit: SUIT_VALUES.HEARTS },
  { id: 16, value: CARD_VALUES.SEVEN, suit: SUIT_VALUES.SPADES },
  { id: 17, value: CARD_VALUES.SEVEN, suit: SUIT_VALUES.CLUBS },
  { id: 18, value: CARD_VALUES.SEVEN, suit: SUIT_VALUES.DIAMONDS },
  { id: 19, value: CARD_VALUES.SEVEN, suit: SUIT_VALUES.HEARTS },
  { id: 20, value: CARD_VALUES.EIGHT, suit: SUIT_VALUES.SPADES },
  { id: 21, value: CARD_VALUES.EIGHT, suit: SUIT_VALUES.CLUBS },
  { id: 22, value: CARD_VALUES.EIGHT, suit: SUIT_VALUES.DIAMONDS },
  { id: 23, value: CARD_VALUES.EIGHT, suit: SUIT_VALUES.HEARTS },
  { id: 24, value: CARD_VALUES.NINE, suit: SUIT_VALUES.SPADES },
  { id: 25, value: CARD_VALUES.NINE, suit: SUIT_VALUES.CLUBS },
  { id: 26, value: CARD_VALUES.NINE, suit: SUIT_VALUES.DIAMONDS },
  { id: 27, value: CARD_VALUES.NINE, suit: SUIT_VALUES.HEARTS },
  { id: 28, value: CARD_VALUES.TEN, suit: SUIT_VALUES.SPADES },
  { id: 29, value: CARD_VALUES.TEN, suit: SUIT_VALUES.CLUBS },
  { id: 30, value: CARD_VALUES.TEN, suit: SUIT_VALUES.DIAMONDS },
  { id: 31, value: CARD_VALUES.TEN, suit: SUIT_VALUES.HEARTS },
  { id: 32, value: CARD_VALUES.JACK, suit: SUIT_VALUES.SPADES },
  { id: 33, value: CARD_VALUES.JACK, suit: SUIT_VALUES.CLUBS },
  { id: 34, value: CARD_VALUES.JACK, suit: SUIT_VALUES.DIAMONDS },
  { id: 35, value: CARD_VALUES.JACK, suit: SUIT_VALUES.HEARTS },
  { id: 36, value: CARD_VALUES.QUEEN, suit: SUIT_VALUES.SPADES },
  { id: 37, value: CARD_VALUES.QUEEN, suit: SUIT_VALUES.CLUBS },
  { id: 38, value: CARD_VALUES.QUEEN, suit: SUIT_VALUES.DIAMONDS },
  { id: 39, value: CARD_VALUES.QUEEN, suit: SUIT_VALUES.HEARTS },
  { id: 40, value: CARD_VALUES.KING, suit: SUIT_VALUES.SPADES },
  { id: 41, value: CARD_VALUES.KING, suit: SUIT_VALUES.CLUBS },
  { id: 42, value: CARD_VALUES.KING, suit: SUIT_VALUES.DIAMONDS },
  { id: 43, value: CARD_VALUES.KING, suit: SUIT_VALUES.HEARTS },
  { id: 44, value: CARD_VALUES.ACE, suit: SUIT_VALUES.SPADES },
  { id: 45, value: CARD_VALUES.ACE, suit: SUIT_VALUES.CLUBS },
  { id: 46, value: CARD_VALUES.ACE, suit: SUIT_VALUES.DIAMONDS },
  { id: 47, value: CARD_VALUES.ACE, suit: SUIT_VALUES.HEARTS },
  { id: 48, value: CARD_VALUES.TWO, suit: SUIT_VALUES.SPADES },
  { id: 49, value: CARD_VALUES.TWO, suit: SUIT_VALUES.CLUBS },
  { id: 50, value: CARD_VALUES.TWO, suit: SUIT_VALUES.DIAMONDS },
  { id: 51, value: CARD_VALUES.TWO, suit: SUIT_VALUES.HEARTS },
];

export default deckOfCards;
